### ISSUE TITLE
Startup Loop after installed automower plugin

### ISSUE THREAD

**Issue by CameronVIE** [nicoduj/homebridge-automower#17]
Hi!
After installing plugin it get following error and HB does not start completely - it is in a starting loop.

57:37 PM] [HomeMatic CCU3] [Core] will cache ccu response to /homebridge/ccu.json
[4/25/2020, 9:57:37 PM] [HomebridgeAutomower] INFO - Creating  Fan Service Automower 315X
[4/25/2020, 9:57:37 PM] Error: Cannot add a Service with the same UUID '00000040-0000-1000-8000-0026BB765291' and subtype 'FanServiceAutomower 315X' as another Service in this Accessory.
    at PlatformAccessory.addService (/usr/local/lib/node_modules/homebridge/lib/platformAccessory.js:55:15)
    at myAutoMowerPlatform.loadMowers (/homebridge/node_modules/homebridge-automower/index.js:169:28)
    at AutoMowerAPI.<anonymous> (/homebridge/node_modules/homebridge-automower/index.js:97:14)
    at AutoMowerAPI.emit (events.js:311:20)
    at Request._callback (/homebridge/node_modules/homebridge-automower/autoMowerAPI.js:129:20)
    at Request.self.callback (/homebridge/node_modules/homebridge-automower/node_modules/request/request.js:185:22)
    at Request.emit (events.js:311:20)
    at Request.<anonymous> (/homebridge/node_modules/homebridge-automower/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:311:20)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-automower/node_modules/request/request.js:1076:12)
[4/25/2020, 9:57:37 PM] Got SIGTERM, shutting down Homebridge...
[4/25/2020, 9:57:37 PM] [HomebridgeAutomower] INFO - shutdown

After removing plugin, HB starts correctly!

Thanx for help
CameronVIE

**Comment by nicoduj** [comment]
Hi, Like I said in the readme / update notice you have to clean the cache either by launching with cleancache option of the plugin once or uninstalling the plugin and removing its cache through homebridge uix option fo example.

**Comment by nicoduj** [comment]
see #19
